version: "3.8"
services:
  db:
    container_name: "ecommerce-db"
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce-db
    ports:
      - "5432:5432"
    volumes:
      - datision-db:/var/lib/postgresql/data

  node_backend:
    container_name: "node_backend"
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=ecommerce-db
      - DB_HOST=localhost
    depends_on:
      - db

volumes:
  datision-db:
    name: datision-db
    driver: local
